export interface RequeteStage {
  _id: String,
  title: String,
  description: String,
  enterprise: String,
  studentName: string,
  school: string,
  studentPresentation: string,
  startDate: Date,
  endDate: Date,
  program: String,
  requirements: String,
  stageType: String,
  hoursPerWeek: Number,
  additionalInfo: String,
  paid: String [],
  skills: String [],
  published: Boolean,
  active: boolean,
  region: String,
  activitySector: String,
  city: String,
  linkToResume: String,
}

